# Generated by Django 3.2.3 on 2021-05-31 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210531_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='published',
            new_name='publish_date',
        ),
    ]
