# Generated by Django 3.2.3 on 2021-05-31 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_published_blogpost_publish_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-publish_date', '-updated', '-created']},
        ),
    ]
